const data = {
  products: [
    {
      name: 'Spiderman',
      slug: 'spiderman-game1',
      image: './images/spidermanimg.jpg',
      edition: 'Game of the Year',
      description: 'best game ever',
      genre: [],
      price: 45,
      distributor: 'Sony',
      comments: [],
      rating: 4.5,
      stock: '2',
    },
    {
      name: 'Spiderman',
      slug: 'spiderman-game2',
      image: './images/spidermanimg.jpg',
      edition: 'Game of the Year',
      description: 'best game ever',
      genre: [],
      price: 45,
      distributor: 'Sony',
      comments: [],
      rating: 4.5,
      stock: '2',
    },
    {
      name: 'Spiderman',
      slug: 'spiderman-game3',
      image: './images/spidermanimg.jpg',
      edition: 'Game of the Year',
      description: 'best game ever',
      genre: [],
      price: 45,
      distributor: 'Sony',
      comments: [],
      rating: 4.5,
      stock: '2',
    },
  ],
};

export default data;
